### ISSUE TITLE
The requested package qordoba/unirest-php could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by hudhafah** [Qordobacode/api-sdk-php#2]
Followed the instruction but got the following error. Please kindly look into it.

$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package qordoba/unirest-php could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by wassemgtk** [comment]
Hi @hudhafah  it’s not going to work without keys and latest version . Happy to give you test keys on the phone or GotToMeeting call. Email me a number and happy to call you.

**Comment by hudhafah** [comment]
My teammate has found alternative with functional SDK so we won't proceed with this. Thanks for the follow up though.
