### ISSUE TITLE
Issue in server response: please remove the line 287 in Connection.php

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [Qordobacode/api-sdk-php#4]
Hi,

in https://github.com/Qordobacode/api-sdk-php/blob/master/src/Qordoba/Connection.php

line number 287

`echo 'HTTP Request "' . $apiUrl .'" Execution Time: ' . round($execution_time, 2) . ' Second(s)' . PHP_EOL;`

Causing issue with json responses from the server please remove this line.

Thanks,
Unnikrishnan B.

**Comment by RadikChernyshov** [comment]
Hey @UnnikrishnanBhargavakurup!

The problem has been fixed. Could you please update the **SDK** using **composer**  ([the latest version](https://packagist.org/packages/qordoba/qordoba-php))

Thank you very much for your attention!
